[theme]
base = "light"
primaryColor = "#3FA34D"
backgroundColor = "#E6F2E6"
secondaryBackgroundColor = "#F3F8F3"
textColor = "#1F3D2B"
font = "sans serif"

[server]
# ESTO ES LO QUE SOLUCIONA EL ERROR DEL COMPONENTE JS
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8080

[browser]
# Evita problemas de telemetría que pueden bloquear la carga
gatherUsageStats = false
